version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "esoft_demo_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "whoscared123"
    ports:
      - "5432:5432"