version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "esoft_demo_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "whoscared123"
    ports:
      - "5555:5432"
    volumes:
      - ./infrastructure/db/001-create-table-client.sql:/docker-entrypoint-initdb.d/001-create-table-client.sql
      - ./infrastructure/db/002-create-table-realtor.sql:/docker-entrypoint-initdb.d/002-create-table-realtor.sql
      - ./infrastructure/db/003-create-table-address.sql:/docker-entrypoint-initdb.d/003-create-table-address.sql
      - ./infrastructure/db/004-create-table-real_estate.sql:/docker-entrypoint-initdb.d/004-create-table-real_estate.sql
      - ./infrastructure/db/005-create-table-offer.sql:/docker-entrypoint-initdb.d/005-create-table-offer.sql
      - ./infrastructure/db/006-create-table-demand.sql:/docker-entrypoint-initdb.d/006-create-table-demand.sql
      - ./infrastructure/db/007-create-table-deal.sql:/docker-entrypoint-initdb.d/007-create-table-deal.sql