create table client (
                        id bigint primary key generated by default as identity,
                        lastname varchar(50) ,
                        firstname varchar(50),
                        patronymic varchar(50),
                        phone varchar(11),
                        email varchar(60)
);