create table realtor (
                         id bigint primary key generated by default as identity,
                         lastname varchar(50) not null ,
                         firstname varchar(50) not null ,
                         patronymic varchar(50) not null,
                         share_of_commission int check ( share_of_commission > -1) check ( share_of_commission < 101 ) not null
);