create table address (
                         id bigint primary key generated by default as identity,
                         type_of_real_estate varchar not null ,
                         city varchar default null,
                         street varchar default null,
                         house varchar default null,
                         apartment_number varchar default null,
                         latitude int default null,
                         longitude int default null
)