create table real_estate (
                             id bigint primary key generated by default as identity,
                             type_of_real_estate varchar not null ,
                             address_id bigint references address(id) not null,
                             floor int default null,
                             rooms int default null,
                             area int default null
)