create table offer (
                       id bigint primary key generated by default as identity,
                       client bigint references client(id) not null ,
                       realtor bigint references realtor(id) not null,
                       real_estate bigint references real_estate(id) not null,
                       price int check (price > -1)
);