create table demand (
                        id bigint primary key generated by default as identity,
                        type_of_real_estate varchar not null ,
                        client bigint references client(id) not null ,
                        realtor bigint references realtor(id) not null,
                        address_id bigint references address(id) not null,
                        min_area int default null,
                        max_area int default null,
                        min_room int default null,
                        max_room int default null,
                        min_float int default null,
                        max_float int default null
)