create table deal (
                      id bigint primary key generated by default as identity,
                      offer bigint references offer(id) not null,
                      demand bigint references demand(id) not null)